project:
  type: website

website:
  title: "do4ds"
  navbar:
    left:
      - index.qmd
      - eda.qmd
      - model.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

