# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_s3(bucket = "do4ds-lab-sdp")
v <- vetiver_pin_read(b, "penguin_body_mass", version = "20230808T094811Z-fe7de")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
